spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  application:
    name: kawaii-keeper
  jpa:
    hibernate:
      ddl-auto: update

api-config:
  bot-token: ${BOT_TOKEN}
  api-base-url: ${API_BASE_URL}
  api-categories:
    - random
    - catgirl
    - foxgirl
    - wolf-girl
    - animal-ears
    - tail
    - tail-with-ribbon
    - tail-from-under-skirt
    - cute
    - cuteness-is-justice
    - blue-archive
    - girl
    - young-girl
    - maid
    - maid-uniform
    - vtuber
    - w-sitting
    - lying-down
    - hands-forming-a-heart
    - wink
    - valentine
    - headphones
    - thigh-high-socks
    - knee-high-socks
    - white-tights
    - black-tights
    - heterochromia
    - uniform
    - sailor-uniform
    - hoodie
    - ribbon
    - white-hair
    - blue-hair
    - long-hair
    - blonde
    - blue-eyes
    - purple-eyes